#!/usr/bin/env node
import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = resolve(rootDir, "manifests/builds.json");

function usage() {
  console.error(`Usage:
  node scripts/openwrts.mjs resolve-matrix [--device all|id | --devices all|id,id] [--branch name]
  node scripts/openwrts.mjs validate-manifest
  node scripts/openwrts.mjs generate-workflows [--check]
  node scripts/openwrts.mjs source-url`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) continue;
    const [key, inline] = token.slice(2).split("=", 2);
    if (inline !== undefined) {
      args[key] = inline;
    } else if (argv[index + 1] && !argv[index + 1].startsWith("--")) {
      args[key] = argv[index + 1];
      index += 1;
    } else {
      args[key] = true;
    }
  }
  return args;
}

function readManifest() {
  return JSON.parse(readFileSync(manifestPath, "utf8"));
}

function unique(values) {
  return [...new Set(values)];
}

function parseDevices(value) {
  const devices = unique(String(value || "all").split(",").map((item) => item.trim()).filter(Boolean));
  if (devices.includes("all") && devices.length > 1) {
    throw new Error("devices cannot combine 'all' with other values.");
  }
  return devices.length ? devices : ["all"];
}

function validateManifest(data) {
  const errors = [];
  if (!data || typeof data !== "object") errors.push("manifest must be an object");
  if (!data?.source?.id || !data?.source?.url || !data?.source?.branch) {
    errors.push("source.id, source.url, and source.branch are required");
  }
  if (!Array.isArray(data?.builds) || data.builds.length === 0) {
    errors.push("builds must be a non-empty array");
  }

  const ids = new Set();
  const cacheScopes = new Set();
  for (const item of data?.builds || []) {
    const label = item.id || "unknown";
    for (const field of ["id", "op_name", "target_config", "app_config", "cache_scope"]) {
      if (!item[field]) errors.push(`${label}: missing ${field}`);
    }
    if (ids.has(item.id)) errors.push(`${label}: duplicate id`);
    ids.add(item.id);
    if (cacheScopes.has(item.cache_scope)) errors.push(`${label}: duplicate cache_scope ${item.cache_scope}`);
    cacheScopes.add(item.cache_scope);
    for (const field of ["target_config", "app_config"]) {
      if (item[field] && !existsSync(resolve(rootDir, item[field]))) {
        errors.push(`${label}: ${field} not found: ${item[field]}`);
      }
    }
  }

  const defaultDevice = data?.workflow?.manual?.default_device || "all";
  if (defaultDevice !== "all" && !ids.has(defaultDevice)) errors.push("workflow.manual.default_device is invalid");
  for (const device of parseDevices(data?.workflow?.schedule?.default_devices || "all")) {
    if (device !== "all" && !ids.has(device)) errors.push(`workflow.schedule.default_devices contains unknown device '${device}'`);
  }
  if (errors.length) throw new Error(`Manifest validation failed:\n- ${errors.join("\n- ")}`);
}

function workflowHeader() {
  return "# This file is generated by `node scripts/openwrts.mjs generate-workflows`.\n# Do not edit workflow input options by hand.\n";
}

function deviceOptions(data) {
  return ["all", ...data.builds.map((item) => item.id)].map((id) => `          - ${id}`).join("\n");
}

function manualWorkflow(data) {
  const defaultDevice = data.workflow?.manual?.default_device || "all";
  return `${workflowHeader()}name: Manual ImmortalWrt Build

on:
  workflow_dispatch:
    inputs:
      device:
        description: Device id from manifests/builds.json, or all.
        required: true
        type: choice
        options:
${deviceOptions(data)}
        default: ${defaultDevice}
      branch:
        description: Override the ImmortalWrt branch. Leave empty to use ${data.source.branch}.
        required: false
        type: string
        default: ""
      upload_release:
        description: Upload firmware to GitHub Releases.
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  resolve:
    runs-on: ubuntu-22.04
    outputs:
      matrix: \${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate generated workflow files
        run: |
          node scripts/openwrts.mjs validate-manifest
          node scripts/openwrts.mjs generate-workflows --check

      - name: Resolve build matrix
        id: matrix
        run: |
          node scripts/openwrts.mjs resolve-matrix \\
            --device "\${{ inputs.device }}" \\
            --branch "\${{ inputs.branch }}"

  build:
    needs: resolve
    strategy:
      fail-fast: false
      matrix: \${{ fromJSON(needs.resolve.outputs.matrix) }}
    name: \${{ matrix.id }}
    uses: ./.github/workflows/build-openwrt.yml
    with:
      branch: \${{ matrix.branch }}
      device: \${{ matrix.id }}
      op_name: \${{ matrix.op_name }}
      target_config: \${{ matrix.target_config }}
      app_config: \${{ matrix.app_config }}
      cache_scope: \${{ matrix.cache_scope }}
      upload_release: \${{ inputs.upload_release }}
    secrets: inherit
`;
}

function scheduledWorkflow(data) {
  const defaultDevices = data.workflow?.schedule?.default_devices || "all";
  return `${workflowHeader()}name: Scheduled ImmortalWrt Release

on:
  workflow_dispatch:
    inputs:
      devices:
        description: Device ids, comma-separated for multiple devices, or all.
        required: true
        type: string
        default: "${defaultDevices}"
      branch:
        description: Override the ImmortalWrt branch. Leave empty to use ${data.source.branch}.
        required: false
        type: string
        default: ""
      upload_release:
        description: Upload firmware to GitHub Releases.
        required: true
        type: boolean
        default: true
  schedule:
    - cron: "23 16 * * 6"

permissions:
  contents: write

jobs:
  resolve:
    runs-on: ubuntu-22.04
    outputs:
      matrix: \${{ steps.matrix.outputs.matrix }}
      upload_release: \${{ steps.matrix.outputs.upload_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate generated workflow files
        run: |
          node scripts/openwrts.mjs validate-manifest
          node scripts/openwrts.mjs generate-workflows --check

      - name: Resolve build matrix
        id: matrix
        env:
          REQUESTED_DEVICES: \${{ github.event.inputs.devices || '${defaultDevices}' }}
          REQUESTED_BRANCH: \${{ github.event.inputs.branch || '' }}
          REQUESTED_UPLOAD_RELEASE: \${{ github.event.inputs.upload_release || 'true' }}
        run: |
          node scripts/openwrts.mjs resolve-matrix \\
            --devices "$REQUESTED_DEVICES" \\
            --branch "$REQUESTED_BRANCH"
          echo "upload_release=$REQUESTED_UPLOAD_RELEASE" >> "$GITHUB_OUTPUT"

  build:
    needs: resolve
    strategy:
      fail-fast: false
      matrix: \${{ fromJSON(needs.resolve.outputs.matrix) }}
    name: \${{ matrix.id }}
    uses: ./.github/workflows/build-openwrt.yml
    with:
      branch: \${{ matrix.branch }}
      device: \${{ matrix.id }}
      op_name: \${{ matrix.op_name }}
      target_config: \${{ matrix.target_config }}
      app_config: \${{ matrix.app_config }}
      cache_scope: \${{ matrix.cache_scope }}
      upload_release: \${{ needs.resolve.outputs.upload_release == 'true' }}
    secrets: inherit
`;
}

function generatedFiles(data) {
  return [
    [".github/workflows/manual-build.yml", manualWorkflow(data)],
    [".github/workflows/schedule-release.yml", scheduledWorkflow(data)],
  ];
}

function resolveMatrix(args) {
  const data = readManifest();
  validateManifest(data);
  const devices = parseDevices(args.devices === undefined ? args.device : args.devices);
  const knownDevices = data.builds.map((item) => item.id);
  const unknown = devices.filter((item) => item !== "all" && !knownDevices.includes(item));
  if (unknown.length) throw new Error(`Unknown devices: ${unknown.join(", ")}. Available devices: ${knownDevices.join(", ")}.`);
  const include = data.builds
    .filter((item) => devices.includes("all") || devices.includes(item.id))
    .map((item) => ({ ...item, branch: args.branch === true || !args.branch ? data.source.branch : args.branch }));
  const output = { matrix: JSON.stringify({ include }) };
  if (process.env.GITHUB_OUTPUT) {
    appendFileSync(process.env.GITHUB_OUTPUT, `matrix=${output.matrix}\n`, "utf8");
  } else {
    console.log(JSON.stringify(output, null, 2));
  }
}

function generateWorkflows(check) {
  const data = readManifest();
  validateManifest(data);
  const mismatches = [];
  for (const [path, content] of generatedFiles(data)) {
    const filePath = resolve(rootDir, path);
    const current = existsSync(filePath) ? readFileSync(filePath, "utf8") : "";
    if (current !== content) {
      mismatches.push(path);
      if (!check) writeFileSync(filePath, content, "utf8");
    }
  }
  if (check && mismatches.length) throw new Error(`Generated files are out of date: ${mismatches.join(", ")}. Run node scripts/openwrts.mjs generate-workflows.`);
  console.log(mismatches.length ? `Updated generated files: ${mismatches.join(", ")}` : "Generated files are up to date.");
}

function main() {
  const [command, ...rest] = process.argv.slice(2);
  const args = parseArgs(rest);
  try {
    if (command === "resolve-matrix") resolveMatrix(args);
    else if (command === "validate-manifest") {
      validateManifest(readManifest());
      console.log("Manifest validation passed.");
    } else if (command === "generate-workflows") generateWorkflows(Boolean(args.check));
    else if (command === "source-url") console.log(readManifest().source.url);
    else {
      usage();
      process.exitCode = 2;
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}

main();
